### ISSUE TITLE
Country MemberSince causing problems

### ISSUE THREAD

**Issue by knjensen** [IWSDevelopers/iws#20]
Following was reported by Maciek, while working on the IWx (AngularJS) Committee module.
```
2016-03-25 14:36:38,711 WARNING [org.apache.cxf.phase.PhaseInterceptorChain] (default task-7) Interceptor for {http://ws.iws.iaeste.net/}committeeWSService#{http://ws.iws.iaeste.net/}processCommittee has thrown exception, unwinding now: org.apache.cxf.interceptor.Fault: Unmarshalling Error: Not a number: null 
	at org.apache.cxf.jaxb.JAXBEncoderDecoder.unmarshall(JAXBEncoderDecoder.java:881)
    [ ... ]
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:370)
	... 47 more
Caused by: javax.xml.bind.UnmarshalException: Not a number: null
 - with linked exception:
[java.lang.NumberFormatException: Not a number: null]
	... 57 more
Caused by: java.lang.NumberFormatException: Not a number: null
	at com.sun.xml.bind.DatatypeConverterImpl._parseInt(DatatypeConverterImpl.java:115)
```
Task is simple, investigate and correct the problem.

**Comment by knjensen** [comment]
By invoking the following command with the XML below, it is possible to replicate the error:

```sh
curl --header "Content-Type: text/xml;charset=ISO-8859-15" --data @committee_request.soap http://localhost:9080/iws-ws/committeeWS?wsdl
```
```xml
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://ws.iws.iaeste.net/">
    <soap:Header/>
    <soap:Body>
        <ns:processCommittee>
            <token>
                <token>f43f4a29cb7e42376f7168d4f746b7951a935dffdde784b68e0e625341447c3e</token>
            </token>
            <request>
                <nationalCommittee>
                    <groupId>a47fd465-bb39-4c8c-8a9e-d51671790567</groupId>
                    <parentId>aa681bc9-0707-4e3c-9cd1-d33c4af13f00</parentId>
                    <groupName>Croatia</groupName>
                    <fullName>null</fullName>
                    <listName>null</listName>
                    <privateList>false</privateList>
                    <privateListReplyTo>REPLY_TO_LIST</privateListReplyTo>
                    <publicList>true</publicList>
                    <publicListReplyTo>REPLY_TO_SENDER</publicListReplyTo>
                    <groupType>NATIONAL</groupType>
                    <description>null</description>
                    <monitoringLevel>NONE</monitoringLevel>
                    <country>
                        <countryCode>HR</countryCode>
                        <countryName>Croatia</countryName>
                        <countryNameFull>Croatia</countryNameFull>
                        <countryNameNative>null</countryNameNative>
                        <nationality>null</nationality>
                        <citizens>null</citizens>
                        <phonecode>null</phonecode>
                        <currency>HRK</currency>
                        <languages>null</languages>
                        <membership>FULL_MEMBER</membership>
                        <memberSince>null</memberSince>
                    </country>
                </nationalCommittee>
                <action>SUSPEND</action>
            </request>
        </ns:processCommittee>
    </soap:Body>
</soap:Envelope>
```
The error is resulting in a stacktrace that looks as follows:
```
16:51:52,335 WARNING [org.apache.cxf.phase.PhaseInterceptorChain] (default task-7) Interceptor for {http://ws.iws.iaeste.net/}committeeWSService#{http://ws.iws.iaeste.net/}processCommittee has thrown exception, unwinding now: org.apache.cxf.interceptor.Fault: Unmarshalling Error: Not a number: null 
	at org.apache.cxf.jaxb.JAXBEncoderDecoder.unmarshall(JAXBEncoderDecoder.java:905)
    [ ... ]
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:415)
	... 48 more
Caused by: javax.xml.bind.UnmarshalException: Not a number: null
 - with linked exception:
[java.lang.NumberFormatException: Not a number: null]
	... 58 more
Caused by: java.lang.NumberFormatException: Not a number: null
	at com.sun.xml.bind.DatatypeConverterImpl._parseInt(DatatypeConverterImpl.java:124)
    [ ... ]
	... 53 more
```
The field memberSince in the Country DTO is specified as follows:
```java
    @XmlElement(required = true, nillable = true)  private Integer memberSince = null;
```
That means problem is present from Scripts, but not from Java requests! Have to investigate that part a bit more. But also provide a proper solution.

**Comment by knjensen** [comment]
With the previous commit, the problem should be resolved. Hopefully the solution is not causing new problems, that also has to be tested. The solution was found [here](http://www.integratingstuff.com/2010/09/06/solving-unmarshalling-problems-with-jaxbcxf/).
